# Site settings
title: Octave Corporation 
description: "Octave corporations’ service is to manage the relationship between students and organizations ensuring that companies are best represented and students are groomed to be competent towards a successful career path."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://octavecorp.me" # the name of your domain
logo_url: http://res.cloudinary.com/octavecorp-me/image/upload/v1524431695/octaveCorporationTransparent800.png

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Octave Corporation
    hero_description: Octave corporations’ service is to manage the relationship between students and organizations ensuring that companies are best represented and students are groomed to be competent towards a successful career path.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +233 54 167 4716
    email: info@octavecorp.me
    address: Lancaster University Ghana, Jungle Road, A&C Mall

# Opening hours
monday_friday: 2:00PM – 4:00PM

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Lancaster Uni Ghana, Jungle Road, Accra
    address_details: http://res.cloudinary.com/octavecorp-me/image/upload/v1524431695/octaveCorporationTransparent800.png

# Social settings
twitter: https://twitter.com/OctaveCorp
instagram: https://instagram.com/octavecoorp
youtube: https://youtube.com/octavecoorp
skype: skype:octavecoorp?userinfo
facebook: https://www.facebook.com/Octave-Corporation-454957284954311/
feed: yes

# Footer
copyright: © 2018 OctaveCorp - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
